// Shared design tokens — farmer app palette (Material 3, from HTML mocks)
export const farmer = {
  primary: '#004625',
  primaryContainer: '#1E5E3A',
  primaryFixed: '#AFF2C2',
  primaryFixedDim: '#94D5A7',
  onPrimary: '#FFFFFF',
  onPrimaryFixed: '#00210F',
  onPrimaryFixedVariant: '#0D512F',
  secondary: '#904D00',
  secondaryContainer: '#FE932C',
  secondaryFixed: '#FFDCC3',
  secondaryFixedDim: '#FFB77D',
  onSecondaryFixed: '#2F1500',
  tertiary: '#003491',
  tertiaryFixed: '#DBE1FF',
  tertiaryFixedDim: '#B4C5FF',
  error: '#BA1A1A',
  errorContainer: '#FFDAD6',
  onErrorContainer: '#93000A',
  background: '#FAF8FF',
  surface: '#FFFFFF',
  surfaceContainerLowest: '#FFFFFF',
  surfaceContainerLow: '#F2F3FF',
  surfaceContainer: '#EAEDFF',
  surfaceContainerHigh: '#E2E7FF',
  surfaceContainerHighest: '#DAE2FD',
  onSurface: '#131B2E',
  onSurfaceVariant: '#404941',
  outline: '#707971',
  outlineVariant: '#C0C9BF',
  inverseSurface: '#283044',
  inverseOnSurface: '#EEF0FF',
  // map-specific
  farmland: '#E8F3EA',
  farmlandDark: '#D5E8D8',
  urban: '#F0F2F8',
  water: '#B6D7F7',
  waterDark: '#89BDF0',
  highway: '#F6993F',
  highwayCasing: '#FED89F',
  road: '#D6DCDE',
  route: '#1D4ED8',
  routeDash: '#93C5FD',
};

// Operator console palette (greener "KisanSetu Centre Operations v2.4")
export const ops = {
  primary: '#004532',
  primaryContainer: '#065F46',
  primaryFixed: '#A6F2D1',
  primaryFixedDim: '#8BD6B6',
  onPrimary: '#FFFFFF',
  secondary: '#006C4A',
  secondaryContainer: '#82F5C1',
  secondaryFixed: '#85F8C4',
  secondaryFixedDim: '#68DBA9',
  onSecondaryContainer: '#00714E',
  tertiary: '#5E3000',
  tertiaryContainer: '#804300',
  tertiaryFixed: '#FFDCC3',
  tertiaryFixedDim: '#FFB77D',
  error: '#BA1A1A',
  errorContainer: '#FFDAD6',
  onErrorContainer: '#93000A',
  background: '#FAF8FF',
  surface: '#FFFFFF',
  surfaceContainerLow: '#F2F3FF',
  surfaceContainer: '#EAEDFF',
  surfaceContainerHigh: '#E2E7FF',
  surfaceContainerHighest: '#DAE2FD',
  surfaceDim: '#D2D9F4',
  onSurface: '#131B2E',
  onSurfaceVariant: '#3F4944',
  outline: '#6F7973',
  outlineVariant: '#BEC9C2',
  inverseSurface: '#283044',
  inverseOnSurface: '#EEF0FF',
  inversePrimary: '#8BD6B6',
};

export const helpline = '1800-180-1551';
